### ISSUE TITLE
How to get v0.9 data

### ISSUE THREAD

**Issue by expectorlin** [gicheonkang/DAN-VisDial#3]
Hi, @Gi-Cheon Kang ! I have a question about the dataset.
How can I get v0.9 data for reimplementing your model?

Thank you very much!

**Comment by gicheonkang** [comment]
@expectorlin Hi, you can download the v0.9 dataset [here](https://visualdialog.org/data). Notice that you need to preprocess the v0.9 dataset same as v1.0 dataset (run prepro.py and utils.py). If you have any question, feel free to reopen the issue. Thanks.
