### ISSUE TITLE
Reproduce your result

### ISSUE THREAD

**Issue by quangvnai** [gicheonkang/DAN-VisDial#6]
Thank you for publishing your code. it's such a great work appearing in EMNLP2019.

Could you provide us the pretrained model so that we can reproduce your result as reported in your paper?

Model | NDCG | MRR | R@1 | R@5 | R@10 | Mean
-- | -- | -- | -- | -- | -- | --
DAN | 0.5759 | 0.6320 | 49.63 | 79.75 | 89.35 | 4.30

**Comment by gicheonkang** [comment]
Hi, @davidnvq  
Sure, I updated the README.md file. You can download the pre-trained model to check the test-std performance. Thank you for your interests.
